PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
INSERT INTO django_migrations VALUES(1,'contenttypes','0001_initial','2026-06-17 11:44:44.243016');
INSERT INTO django_migrations VALUES(2,'auth','0001_initial','2026-06-17 11:44:44.250317');
INSERT INTO django_migrations VALUES(3,'admin','0001_initial','2026-06-17 11:44:44.264905');
INSERT INTO django_migrations VALUES(4,'admin','0002_logentry_remove_auto_add','2026-06-17 11:44:44.270658');
INSERT INTO django_migrations VALUES(5,'admin','0003_logentry_add_action_flag_choices','2026-06-17 11:44:44.274212');
INSERT INTO django_migrations VALUES(6,'contenttypes','0002_remove_content_type_name','2026-06-17 11:44:44.282186');
INSERT INTO django_migrations VALUES(7,'auth','0002_alter_permission_name_max_length','2026-06-17 11:44:44.287324');
INSERT INTO django_migrations VALUES(8,'auth','0003_alter_user_email_max_length','2026-06-17 11:44:44.292223');
INSERT INTO django_migrations VALUES(9,'auth','0004_alter_user_username_opts','2026-06-17 11:44:44.296379');
INSERT INTO django_migrations VALUES(10,'auth','0005_alter_user_last_login_null','2026-06-17 11:44:44.302009');
INSERT INTO django_migrations VALUES(11,'auth','0006_require_contenttypes_0002','2026-06-17 11:44:44.303050');
INSERT INTO django_migrations VALUES(12,'auth','0007_alter_validators_add_error_messages','2026-06-17 11:44:44.306516');
INSERT INTO django_migrations VALUES(13,'auth','0008_alter_user_username_max_length','2026-06-17 11:44:44.311678');
INSERT INTO django_migrations VALUES(14,'auth','0009_alter_user_last_name_max_length','2026-06-17 11:44:44.317000');
INSERT INTO django_migrations VALUES(15,'auth','0010_alter_group_name_max_length','2026-06-17 11:44:44.321544');
INSERT INTO django_migrations VALUES(16,'auth','0011_update_proxy_permissions','2026-06-17 11:44:44.324928');
INSERT INTO django_migrations VALUES(17,'auth','0012_alter_user_first_name_max_length','2026-06-17 11:44:44.329866');
INSERT INTO django_migrations VALUES(18,'shop','0001_initial','2026-06-17 11:44:44.340508');
INSERT INTO django_migrations VALUES(19,'user_management','0001_initial','2026-06-17 11:44:44.352466');
INSERT INTO django_migrations VALUES(20,'order','0001_initial','2026-06-17 11:44:44.366730');
INSERT INTO django_migrations VALUES(21,'sessions','0001_initial','2026-06-17 11:44:44.368960');
INSERT INTO django_migrations VALUES(22,'user_management','0002_rename_last_viewed_books_lastviewedbooks','2026-06-21 13:35:50.044822');
INSERT INTO django_migrations VALUES(23,'shop','0002_rename_address_publisher_city','2026-06-24 11:14:46.243922');
INSERT INTO django_migrations VALUES(24,'shop','0003_book_description_alter_book_author','2026-06-25 10:36:10.239813');
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
INSERT INTO django_admin_log VALUES(1,'1','Taras Sh',1,'[{"added": {}}]',7,1,'2026-06-21 11:52:30.291550');
INSERT INTO django_admin_log VALUES(2,'2','Олександр Михед',1,'[{"added": {}}]',7,1,'2026-06-21 11:54:04.620920');
INSERT INTO django_admin_log VALUES(3,'3','Любко Дереш',1,'[{"added": {}}]',7,1,'2026-06-21 11:54:33.032844');
INSERT INTO django_admin_log VALUES(4,'4','Сергій Жадан',1,'[{"added": {}}]',7,1,'2026-06-21 11:54:47.624562');
INSERT INTO django_admin_log VALUES(5,'5','Настасья Мілевська',1,'[{"added": {}}]',7,1,'2026-06-21 11:55:06.159923');
INSERT INTO django_admin_log VALUES(6,'1','Лесь Подерв’янський',2,'[{"changed": {"fields": ["First name", "Last name", "Biography"]}}]',7,1,'2026-06-21 11:55:52.860273');
INSERT INTO django_admin_log VALUES(7,'1','Vivat',1,'[{"added": {}}]',10,1,'2026-06-21 11:59:13.729590');
INSERT INTO django_admin_log VALUES(8,'1','Художня література',1,'[{"added": {}}]',9,1,'2026-06-21 12:14:58.499130');
INSERT INTO django_admin_log VALUES(9,'1','Астра',1,'[{"added": {}}]',8,1,'2026-06-21 12:15:09.058915');
INSERT INTO django_admin_log VALUES(10,'2','КСД',1,'[{"added": {}}]',10,1,'2026-06-21 12:17:40.408127');
INSERT INTO django_admin_log VALUES(11,'2','Понтиїзм',1,'[{"added": {}}]',8,1,'2026-06-21 12:18:12.331198');
INSERT INTO django_admin_log VALUES(12,'2','Художня проза',1,'[{"added": {}}]',9,1,'2026-06-21 12:19:15.180255');
INSERT INTO django_admin_log VALUES(13,'1','Поезія',2,'[{"changed": {"fields": ["Name"]}}]',9,1,'2026-06-21 12:20:06.267131');
INSERT INTO django_admin_log VALUES(14,'3','Детектив',1,'[{"added": {}}]',9,1,'2026-06-21 12:20:22.101834');
INSERT INTO django_admin_log VALUES(15,'4','Фентезі',1,'[{"added": {}}]',9,1,'2026-06-21 12:20:27.541673');
INSERT INTO django_admin_log VALUES(16,'5','Пʼєса',1,'[{"added": {}}]',9,1,'2026-06-21 12:20:48.870665');
INSERT INTO django_admin_log VALUES(17,'3','Видавництво Старого Лева',1,'[{"added": {}}]',10,1,'2026-06-21 12:25:19.353520');
INSERT INTO django_admin_log VALUES(18,'3','Миротворець',1,'[{"added": {}}]',8,1,'2026-06-21 12:26:22.171897');
INSERT INTO django_admin_log VALUES(19,'4','Пісні про любов та вічність',1,'[{"added": {}}]',8,1,'2026-06-21 12:27:04.788533');
INSERT INTO django_admin_log VALUES(20,'5','Гімн демократичної молоді',1,'[{"added": {}}]',8,1,'2026-06-21 12:27:54.541629');
INSERT INTO django_admin_log VALUES(21,'6','Життя Марії',1,'[{"added": {}}]',8,1,'2026-06-21 13:01:49.798144');
INSERT INTO django_admin_log VALUES(22,'7','PSI*',1,'[{"added": {}}]',8,1,'2026-06-21 13:02:46.146828');
INSERT INTO django_admin_log VALUES(23,'8','Рух життя, або Динамо',1,'[{"added": {}}]',8,1,'2026-06-21 13:03:44.484774');
INSERT INTO django_admin_log VALUES(24,'9','Герой нашого часу',1,'[{"added": {}}]',8,1,'2026-06-21 13:04:27.405285');
INSERT INTO django_admin_log VALUES(25,'10','Павлік Морозов',1,'[{"added": {}}]',8,1,'2026-06-21 13:05:07.593488');
INSERT INTO django_admin_log VALUES(26,'1','DeliveryAddress object (1)',1,'[{"added": {}}]',12,1,'2026-06-21 16:17:23.433193');
INSERT INTO django_admin_log VALUES(27,'2','admin - Kiyv, av. Shevchenka, 3, 02001',1,'[{"added": {}}]',12,1,'2026-06-21 16:20:52.138017');
INSERT INTO django_admin_log VALUES(28,'1','Order object (1)',1,'[{"added": {}}]',14,1,'2026-06-21 16:21:29.733915');
INSERT INTO django_admin_log VALUES(29,'1','OrderDetails object (1)',1,'[{"added": {}}]',15,1,'2026-06-21 16:22:53.741430');
INSERT INTO django_admin_log VALUES(30,'2','Order object (2)',1,'[{"added": {}}]',14,1,'2026-06-21 16:23:32.018576');
INSERT INTO django_admin_log VALUES(31,'2','OrderDetails object (2)',1,'[{"added": {}}]',15,1,'2026-06-21 16:23:47.383657');
INSERT INTO django_admin_log VALUES(32,'3','OrderDetails object (3)',1,'[{"added": {}}]',15,1,'2026-06-21 16:23:56.473437');
INSERT INTO django_admin_log VALUES(33,'4','OrderDetails object (4)',1,'[{"added": {}}]',15,1,'2026-06-21 16:25:30.955300');
INSERT INTO django_admin_log VALUES(34,'6','Життя Марії by Сергій Жадан, Настасья Мілевська',2,'[{"changed": {"fields": ["Author"]}}]',8,1,'2026-06-24 11:04:19.971012');
INSERT INTO django_admin_log VALUES(35,'1','admin - Астра - 5',1,'[{"added": {}}]',11,1,'2026-06-24 11:16:42.519355');
INSERT INTO django_admin_log VALUES(36,'2','admin - Життя Марії - 5',1,'[{"added": {}}]',11,1,'2026-06-24 11:17:01.759619');
INSERT INTO django_admin_log VALUES(37,'3','admin - Життя Марії - 1',1,'[{"added": {}}]',11,1,'2026-06-24 11:17:15.246179');
INSERT INTO django_admin_log VALUES(38,'4','Пісні про любов та вічність',1,'[{"added": {}}]',11,1,'2026-06-24 13:46:09.702527');
INSERT INTO django_admin_log VALUES(39,'5','Пісні про любов та вічність',1,'[{"added": {}}]',11,1,'2026-06-24 13:46:21.929860');
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
INSERT INTO django_content_type VALUES(1,'admin','logentry');
INSERT INTO django_content_type VALUES(2,'auth','group');
INSERT INTO django_content_type VALUES(3,'auth','permission');
INSERT INTO django_content_type VALUES(4,'auth','user');
INSERT INTO django_content_type VALUES(5,'contenttypes','contenttype');
INSERT INTO django_content_type VALUES(6,'sessions','session');
INSERT INTO django_content_type VALUES(7,'shop','author');
INSERT INTO django_content_type VALUES(8,'shop','book');
INSERT INTO django_content_type VALUES(9,'shop','category');
INSERT INTO django_content_type VALUES(10,'shop','publisher');
INSERT INTO django_content_type VALUES(11,'shop','rating');
INSERT INTO django_content_type VALUES(12,'user_management','deliveryaddress');
INSERT INTO django_content_type VALUES(13,'user_management','lastviewedbooks');
INSERT INTO django_content_type VALUES(14,'order','order');
INSERT INTO django_content_type VALUES(15,'order','orderdetails');
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
INSERT INTO auth_permission VALUES(1,1,'add_logentry','Can add log entry');
INSERT INTO auth_permission VALUES(2,1,'change_logentry','Can change log entry');
INSERT INTO auth_permission VALUES(3,1,'delete_logentry','Can delete log entry');
INSERT INTO auth_permission VALUES(4,1,'view_logentry','Can view log entry');
INSERT INTO auth_permission VALUES(5,3,'add_permission','Can add permission');
INSERT INTO auth_permission VALUES(6,3,'change_permission','Can change permission');
INSERT INTO auth_permission VALUES(7,3,'delete_permission','Can delete permission');
INSERT INTO auth_permission VALUES(8,3,'view_permission','Can view permission');
INSERT INTO auth_permission VALUES(9,2,'add_group','Can add group');
INSERT INTO auth_permission VALUES(10,2,'change_group','Can change group');
INSERT INTO auth_permission VALUES(11,2,'delete_group','Can delete group');
INSERT INTO auth_permission VALUES(12,2,'view_group','Can view group');
INSERT INTO auth_permission VALUES(13,4,'add_user','Can add user');
INSERT INTO auth_permission VALUES(14,4,'change_user','Can change user');
INSERT INTO auth_permission VALUES(15,4,'delete_user','Can delete user');
INSERT INTO auth_permission VALUES(16,4,'view_user','Can view user');
INSERT INTO auth_permission VALUES(17,5,'add_contenttype','Can add content type');
INSERT INTO auth_permission VALUES(18,5,'change_contenttype','Can change content type');
INSERT INTO auth_permission VALUES(19,5,'delete_contenttype','Can delete content type');
INSERT INTO auth_permission VALUES(20,5,'view_contenttype','Can view content type');
INSERT INTO auth_permission VALUES(21,6,'add_session','Can add session');
INSERT INTO auth_permission VALUES(22,6,'change_session','Can change session');
INSERT INTO auth_permission VALUES(23,6,'delete_session','Can delete session');
INSERT INTO auth_permission VALUES(24,6,'view_session','Can view session');
INSERT INTO auth_permission VALUES(25,7,'add_author','Can add author');
INSERT INTO auth_permission VALUES(26,7,'change_author','Can change author');
INSERT INTO auth_permission VALUES(27,7,'delete_author','Can delete author');
INSERT INTO auth_permission VALUES(28,7,'view_author','Can view author');
INSERT INTO auth_permission VALUES(29,9,'add_category','Can add category');
INSERT INTO auth_permission VALUES(30,9,'change_category','Can change category');
INSERT INTO auth_permission VALUES(31,9,'delete_category','Can delete category');
INSERT INTO auth_permission VALUES(32,9,'view_category','Can view category');
INSERT INTO auth_permission VALUES(33,10,'add_publisher','Can add publisher');
INSERT INTO auth_permission VALUES(34,10,'change_publisher','Can change publisher');
INSERT INTO auth_permission VALUES(35,10,'delete_publisher','Can delete publisher');
INSERT INTO auth_permission VALUES(36,10,'view_publisher','Can view publisher');
INSERT INTO auth_permission VALUES(37,8,'add_book','Can add book');
INSERT INTO auth_permission VALUES(38,8,'change_book','Can change book');
INSERT INTO auth_permission VALUES(39,8,'delete_book','Can delete book');
INSERT INTO auth_permission VALUES(40,8,'view_book','Can view book');
INSERT INTO auth_permission VALUES(41,11,'add_rating','Can add rating');
INSERT INTO auth_permission VALUES(42,11,'change_rating','Can change rating');
INSERT INTO auth_permission VALUES(43,11,'delete_rating','Can delete rating');
INSERT INTO auth_permission VALUES(44,11,'view_rating','Can view rating');
INSERT INTO auth_permission VALUES(45,12,'add_deliveryaddress','Can add delivery address');
INSERT INTO auth_permission VALUES(46,12,'change_deliveryaddress','Can change delivery address');
INSERT INTO auth_permission VALUES(47,12,'delete_deliveryaddress','Can delete delivery address');
INSERT INTO auth_permission VALUES(48,12,'view_deliveryaddress','Can view delivery address');
INSERT INTO auth_permission VALUES(49,13,'add_last_viewed_books','Can add last_viewed_books');
INSERT INTO auth_permission VALUES(50,13,'change_last_viewed_books','Can change last_viewed_books');
INSERT INTO auth_permission VALUES(51,13,'delete_last_viewed_books','Can delete last_viewed_books');
INSERT INTO auth_permission VALUES(52,13,'view_last_viewed_books','Can view last_viewed_books');
INSERT INTO auth_permission VALUES(53,14,'add_order','Can add order');
INSERT INTO auth_permission VALUES(54,14,'change_order','Can change order');
INSERT INTO auth_permission VALUES(55,14,'delete_order','Can delete order');
INSERT INTO auth_permission VALUES(56,14,'view_order','Can view order');
INSERT INTO auth_permission VALUES(57,15,'add_orderdetails','Can add order details');
INSERT INTO auth_permission VALUES(58,15,'change_orderdetails','Can change order details');
INSERT INTO auth_permission VALUES(59,15,'delete_orderdetails','Can delete order details');
INSERT INTO auth_permission VALUES(60,15,'view_orderdetails','Can view order details');
INSERT INTO auth_permission VALUES(61,13,'add_lastviewedbooks','Can add last viewed books');
INSERT INTO auth_permission VALUES(62,13,'change_lastviewedbooks','Can change last viewed books');
INSERT INTO auth_permission VALUES(63,13,'delete_lastviewedbooks','Can delete last viewed books');
INSERT INTO auth_permission VALUES(64,13,'view_lastviewedbooks','Can view last viewed books');
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "first_name" varchar(150) NOT NULL);
INSERT INTO auth_user VALUES(1,'pbkdf2_sha256$1200000$49ZDDZo5QgYSarfWun0kwW$PeEvlN+Dw5z24zc+KBtYEZPWBrHWy2Yu6p7zFMHHqkQ=','2026-06-25 10:38:47.393632',1,'admin','','admin@example.com',1,1,'2026-06-17 13:10:30.445640','');
CREATE TABLE IF NOT EXISTS "shop_author" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "first_name" varchar(50) NOT NULL, "last_name" varchar(50) NOT NULL, "biography" text NOT NULL);
INSERT INTO shop_author VALUES(1,'Лесь','Подерв’янський',unistr('Людина, яка гармонійно поєднує в собі дві різні іпостасі: поважного художника та скандального, епатажного й шокуючого письменника. Він не заморочується над тим, які слова підбирати, що в усній, що в письмовій мові. Тому обережно: нецензурна лексика. Але він підходить до цього особливо, а всі гострі словечка майстерно прописує в кожному тексті. Творчість Леся Подерв’янського – яскраве зображення наших пороків, гріхів, національних рис, комплексів та проблем.\u000d\u000a\u000d\u000aВарто прочитати: «Рух життя, або Динамо», «Герой нашого часу», Гамлєт», «Павлік Морозов».'));
INSERT INTO shop_author VALUES(2,'Олександр','Михед',unistr('Молодий діяч у свої 27 вже досягнув небачених успіхів: публікації у провідних українських та іноземних ЗМІ, його проект «АмнезіЯ project: відкрита платформа» увійшов у сімку найкращих поетів світу.Після виходу його книг у світ, не в одного українського читача перевернулись уявлення про українську книжку. Адже Михед не вважає себе письменником у звичному значенні слова, а у своїй мультивекторній роботі він поєднує літературу, кінематограф й мистецтво у єдину гримучу суміш.\u000d\u000a\u000d\u000aВарто прочитати: «Астра», «Понтиїзм», АмнезіЯ».'));
INSERT INTO shop_author VALUES(3,'Любко','Дереш',unistr('Це, напевно, один із найзагадковіших та найекзотичніших письменників України. Свою першу книгу він написав ще у 15. За що його називають «феноменом української літератури». Творчість Дереша змушує людину думати, усвідомлювати себе, усвідомлювати світ, себе в ньому. Його книги важко назвати випадковими, а відокремити читача від автора майже неможливо.\u000d\u000a\u000d\u000aВарто прочитати: синайський цикл «Миротворець», «Остання любов Асури Махараджа», «Пісні про любов та вічність».'));
INSERT INTO shop_author VALUES(4,'Сергій','Жадан',unistr('«Голос Сходу», так часто називають Жадана. І не тільки тому, що він родом із Луганської області, а тому, що його література має присмак «пролетарщини», гнилої радянщини у свідомості покалічених людей. Естетика книг та їх демократичне наповнення свідчать про відвертого та щирого письменника. Мова пересипана гострим слівцем, але хто власне заперечить, що такою є вся українська мова сучасності. У його книгах – портрет українців: не зафотошоплений, брудний, чесний та до непристойності відвертий.\u000d\u000a\u000d\u000aВарто прочитати: проза – «Месопотамія», «Ворошиловоград», «Біґ Мак», «Гімн демократичної молоді», «Anarchy in the UKR», поезія – «Життя Марії», «Вогнепальні й ножові», «Ефіопія».\u000d\u000a\u000d\u000aТакож радимо прослухати спільний музичний альбом із «Собаками в космосі»: «Бийся за неї».'));
INSERT INTO shop_author VALUES(5,'Настасья','Мілевська',unistr('Тендітну харківську поетесу по праву вважають найемоційнішою на літературній сцені України. Її виступи – своєрідні моноспектаклі, які «прошивають» наскрізь слухача. Поезія залишає після себе незрівняний післясмак. Адже для неї написання – це своєрідний священний ритуал. Її творчість симбіоз літератури та театру, що вражає силою слова та неймовірною щирістю.\u000d\u000a\u000d\u000aВарто прочитати: «PSI*».'));
CREATE TABLE IF NOT EXISTS "shop_category" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL);
INSERT INTO shop_category VALUES(1,'Поезія');
INSERT INTO shop_category VALUES(2,'Художня проза');
INSERT INTO shop_category VALUES(3,'Детектив');
INSERT INTO shop_category VALUES(4,'Фентезі');
INSERT INTO shop_category VALUES(5,'Пʼєса');
CREATE TABLE IF NOT EXISTS "shop_publisher" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "city" varchar(200) NOT NULL, "website" varchar(200) NOT NULL);
INSERT INTO shop_publisher VALUES(1,'Vivat','yjhfs','https://sefhksf.com');
INSERT INTO shop_publisher VALUES(2,'КСД','kygjg','https://KSD.ua');
INSERT INTO shop_publisher VALUES(3,'Видавництво Старого Лева','Lviv','https://LEV.com');
CREATE TABLE IF NOT EXISTS "shop_book_author" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "book_id" bigint NOT NULL REFERENCES "shop_book" ("id") DEFERRABLE INITIALLY DEFERRED, "author_id" bigint NOT NULL REFERENCES "shop_author" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO shop_book_author VALUES(1,1,2);
INSERT INTO shop_book_author VALUES(2,2,2);
INSERT INTO shop_book_author VALUES(3,3,3);
INSERT INTO shop_book_author VALUES(4,4,2);
INSERT INTO shop_book_author VALUES(5,5,4);
INSERT INTO shop_book_author VALUES(6,6,4);
INSERT INTO shop_book_author VALUES(7,7,5);
INSERT INTO shop_book_author VALUES(8,8,1);
INSERT INTO shop_book_author VALUES(9,9,1);
INSERT INTO shop_book_author VALUES(10,10,1);
INSERT INTO shop_book_author VALUES(11,6,5);
CREATE TABLE IF NOT EXISTS "shop_book_category" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "book_id" bigint NOT NULL REFERENCES "shop_book" ("id") DEFERRABLE INITIALLY DEFERRED, "category_id" bigint NOT NULL REFERENCES "shop_category" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO shop_book_category VALUES(1,1,1);
INSERT INTO shop_book_category VALUES(2,2,1);
INSERT INTO shop_book_category VALUES(3,3,3);
INSERT INTO shop_book_category VALUES(4,4,1);
INSERT INTO shop_book_category VALUES(5,5,2);
INSERT INTO shop_book_category VALUES(6,6,1);
INSERT INTO shop_book_category VALUES(7,7,1);
INSERT INTO shop_book_category VALUES(8,8,1);
INSERT INTO shop_book_category VALUES(9,8,5);
INSERT INTO shop_book_category VALUES(10,9,5);
INSERT INTO shop_book_category VALUES(11,10,5);
CREATE TABLE IF NOT EXISTS "shop_rating" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "rating" integer unsigned NOT NULL CHECK ("rating" >= 0), "feedback" text NOT NULL, "book_id" bigint NOT NULL REFERENCES "shop_book" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO shop_rating VALUES(1,5,'resjgfkmhgv',1,1);
INSERT INTO shop_rating VALUES(2,5,'utfkhg',6,1);
INSERT INTO shop_rating VALUES(3,1,'hdfhg,yzhdxfgfchvjbj',6,1);
INSERT INTO shop_rating VALUES(4,2,'hfdchgvhmbn',4,1);
INSERT INTO shop_rating VALUES(5,1,'khtgdhgcmn',4,1);
CREATE TABLE IF NOT EXISTS "user_management_deliveryaddress" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "postal_code" varchar(20) NOT NULL, "city" varchar(100) NOT NULL, "street" varchar(200) NOT NULL, "branch" varchar(100) NULL, "owner_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO user_management_deliveryaddress VALUES(1,'03020','Kiyv','Maidan','321',1);
INSERT INTO user_management_deliveryaddress VALUES(2,'02001','Kiyv','av. Shevchenka, 3','321',1);
CREATE TABLE IF NOT EXISTS "user_management_lastviewedbooks" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "book_id" bigint NOT NULL REFERENCES "shop_book" ("id") DEFERRABLE INITIALLY DEFERRED, "owner_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "order_order" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "order_date" datetime NOT NULL, "status" varchar(20) NOT NULL, "total_price" decimal NOT NULL, "payment_method" varchar(50) NOT NULL, "payment_status" varchar(20) NOT NULL, "ttn" varchar(100) NULL, "delivery_address_id" bigint NOT NULL REFERENCES "user_management_deliveryaddress" ("id") DEFERRABLE INITIALLY DEFERRED, "owner_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO order_order VALUES(1,'2026-06-21 16:21:29.732261','shipped',1050,'Cash','pending','875647637',1,1);
INSERT INTO order_order VALUES(2,'2026-06-21 16:23:32.017229','processing',430,'Card','completed','8657643768',2,1);
CREATE TABLE IF NOT EXISTS "order_orderdetails" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "quantity" integer unsigned NOT NULL CHECK ("quantity" >= 0), "price" decimal NOT NULL, "book_id" bigint NOT NULL REFERENCES "shop_book" ("id") DEFERRABLE INITIALLY DEFERRED, "order_id" bigint NOT NULL REFERENCES "order_order" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO order_orderdetails VALUES(1,1,200,2,1);
INSERT INTO order_orderdetails VALUES(2,1,537,7,1);
INSERT INTO order_orderdetails VALUES(3,2,1000,3,2);
INSERT INTO order_orderdetails VALUES(4,1,436,9,2);
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
INSERT INTO django_session VALUES('b8cjzemc8au7ojxx4thukt9yl3nstzlu','.eJxVjEEOwiAQRe_C2hBqYQCX7j0DmYFBqgaS0q6Md7dNutDtf-_9twi4LiWsnecwJXERgzj9boTxyXUH6YH13mRsdZknkrsiD9rlrSV-XQ_376BgL1ttTAT0No_EypJVwHZIzJyJks4mgyYw0QGkTcAzGOWiHZ0mpUYPHsTnCwKLOBU:1wZq2S:dJowfRZwnDcrHh3cl5zzwY-m9QqqRqOg5HBcb5cA3Ac','2026-07-01 13:10:40.754847');
INSERT INTO django_session VALUES('vd9ck3dh8jixtpiqmf6y8xxlgne4fpdg','.eJxVjEEOwiAQRe_C2hBqYQCX7j0DmYFBqgaS0q6Md7dNutDtf-_9twi4LiWsnecwJXERgzj9boTxyXUH6YH13mRsdZknkrsiD9rlrSV-XQ_376BgL1ttTAT0No_EypJVwHZIzJyJks4mgyYw0QGkTcAzGOWiHZ0mpUYPHsTnCwKLOBU:1wbJSE:6RfFShOqLTR85Hoj1HzrqTDe8UXwSPZpcbT5N6sb5S0','2026-07-05 14:47:22.768394');
INSERT INTO django_session VALUES('hnz6j148lp3wj78adkxbzj4ycputr9v1','.eJxVjEEOwiAQRe_C2hBqYQCX7j0DmYFBqgaS0q6Md7dNutDtf-_9twi4LiWsnecwJXERgzj9boTxyXUH6YH13mRsdZknkrsiD9rlrSV-XQ_376BgL1ttTAT0No_EypJVwHZIzJyJks4mgyYw0QGkTcAzGOWiHZ0mpUYPHsTnCwKLOBU:1wchTr:PtE_FFia_bmCW4qNkf1xCbcxxG8vdCuMNIJOAh-L-3k','2026-07-09 10:38:47.394731');
CREATE TABLE IF NOT EXISTS "shop_book" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(200) NOT NULL, "isbn" varchar(13) NOT NULL UNIQUE, "publication_date" date NOT NULL, "added_date" datetime NOT NULL, "in_stock" integer unsigned NOT NULL CHECK ("in_stock" >= 0), "price" decimal NOT NULL, "language" varchar(50) NOT NULL, "calculated_avg_rating" decimal NOT NULL, "publisher_id" bigint NOT NULL REFERENCES "shop_publisher" ("id") DEFERRABLE INITIALLY DEFERRED, "description" text NOT NULL);
INSERT INTO shop_book VALUES(1,'Астра','1231425','2026-06-08','2026-06-21 12:15:09.055472',6,230,'Українська',0,1,'«Астра» — це захоплива історія життя Віктора Варецького, розказана ним самим. Історія пошуку відповідей на запитання, які краще не ставити. Пошук правди, на шляху до якої губиш усіх, кого любив. І розумієш: усе вигадка, все ілюзія. Мандрівка дорогою, що веде серце темряви, в основу світобудови.');
INSERT INTO shop_book VALUES(2,'Понтиїзм','86548646','2025-11-04','2026-06-21 12:18:12.328033',12,430,'Українська',0,2,'«Понтиїзм» – це історії про черговий кінець світу у країні, життя в якій уже давно є безкінечним апокаліпсисом. Оповіді про прірву, що ховається за кожним полотном – хоч асфальтом, хоч картиною. Казки про любов, зраду, кров, ненависть, м’ясо і шлюб. Хроніки віртуальної війни під проводом віртуальних генералів невіртуальної держави. Проповіді жорстокого вірування в понти, яким поклоняється більшість країни.');
INSERT INTO shop_book VALUES(3,'Миротворець','486756','2026-06-21','2026-06-21 12:26:22.169641',3,440,'Українська',0,3,'Нова книжка молодого українського письменника складається з двох повістей та оповідань. Перед нами постає зовсім несподіваний і трохи загадковий Любко Дереш... "Миротворець" - дивні історії, сумні та загадкові, леймотивом яких звучить філософська думка: "ГЕНІЇ ТА ГЕРОЇ ЗАВЖДИ САМОТНІ..."');
INSERT INTO shop_book VALUES(4,'Пісні про любов та вічність','242587487','2026-06-10','2026-06-21 12:27:04.785981',5,330,'Українська',0,3,unistr('Любко Дереш, як завжди, інтригує, ставить у своїх текстах запитання, на які дає парадоксальні відповіді. За які принципи треба триматись у цьому житті? І чи потрібні вони взагалі? У чому справжня цінність людини? До чого призводять пошуки глибинних смислів буття?\u000a\u000aЛюбко Дереш пропонує шукати свої власні відповіді на питання, що ставлять пісні про любов і вічність.'));
INSERT INTO shop_book VALUES(5,'Гімн демократичної молоді','3456789','2025-09-01','2026-06-21 12:27:54.538917',9,350,'Українскька',0,1,unistr('Герої збірки оповідань Сергія Жадана постійно шукають спосіб швидко заробити й вибратися з безгрошів’я на початку двотисячних. Вони відкривають гей-клуби, беруться за сумнівні підробітки, намагаються провернути дивні схеми й постійно опиняються в неприємностях. В оповіданнях поєднуються нові авантюри, випадкові знайомства, алкоголь, хаотичні поїздки й люди, які вперто вірять, що наступна геніальна ідея точно спрацює.\u000a\u000aЗа цими абсурдними пригодами поступово відкривається життя покоління, яке намагається знайти себе в реальності, де старі правила вже не працюють, а нові ще ніхто не вигадав. Книга сподобається шанувальникам сучасної української прози, сатиричних історій та чорного гумору.'));
INSERT INTO shop_book VALUES(6,'Життя Марії','565466g','2025-11-09','2026-06-21 13:01:49.792901',1,280,'Українська',0,2,unistr('Книга "Життя Марії" – Роздуми про людяність та порозуміння\u000aСергій Жадан є видатним українським поетом та прозаїком, який приніс значний внесок у сучасну українську літературу. Його твори, включаючи збірку "Життя Марії", вразливо й потужно спілкуються зі своїми читачами, переплітаючи важливі мотиви та думки.'));
INSERT INTO shop_book VALUES(7,'PSI*','64689859','2025-05-05','2026-06-21 13:02:46.144249',11,189,'Українська',0,1,'«PSI*» — це дебютна поетична збірка харківської поетеси та режисерки Настасьї Мілевської, що вийшла у 2014 році. Її творчість відзначається емоційністю, інтимною лірикою та часто балансує на межі літератури й моноспектаклю.');
INSERT INTO shop_book VALUES(8,'Рух життя, або Динамо','6543865462','2026-03-09','2026-06-21 13:03:44.483424',13,629.990000000000009,'Українська',0,3,unistr('Лесь Подерв’янський (нар. 1952 р.) — скандально відомий український письменник і художник. Його епатажні п’єси, що були спочатку записані на аудіокасетах, принесли йому широку популярність. Тепер з його творами можна ознайомитися на сторінках книжок. Читаючи Подерв’янського, ви відкриєте для себе, що його герої, на жаль, не такі вже нереальні, як це може здатися на перший погляд, а тонка іронія та гумор автора дозволять вам ще і ще раз посміхнутися над трагікомізмом нашого життя.\u000a'));
INSERT INTO shop_book VALUES(9,'Герой нашого часу','7684763','2025-06-18','2026-06-21 13:04:27.402431',5,339,'Українська',0,2,unistr('Лесь Подерв’янський (нар. 1952 р.) — скандально відомий український письменник і художник. Його епатажні п’єси, що були спочатку записані на аудіокасетах, принесли йому широку популярність. Тепер з його творами можна ознайомитися на сторінках книжок. Читаючи Подерв’янського, ви відкриєте для себе, що його герої, на жаль, не такі вже нереальні, як це може здатися на перший погляд, а тонка іронія та гумор автора дозволять вам ще і ще раз посміхнутися над трагікомізмом нашого життя.\u000a'));
INSERT INTO shop_book VALUES(10,'Павлік Морозов','7875468375','2026-06-21','2026-06-21 13:05:07.591016',10,361.9000000000000342,'Українська',0,1,'Лесь Подерв’янський (нар. 1952 р.) — скандально відомий український письменник і художник. Його епатажні п’єси, що були спочатку записані на аудіокасетах, принесли йому широку популярність. Тепер з його творами можна ознайомитися на сторінках книжок. Читаючи Подерв’янського, ви відкриєте для себе, що його герої, на жаль, не такі вже нереальні, як це може здатися на перший погляд, а тонка іронія та гумор автора дозволять вам ще і ще раз посміхнутися над трагікомізмом нашого життя.');
INSERT INTO sqlite_sequence VALUES('django_migrations',24);
INSERT INTO sqlite_sequence VALUES('django_admin_log',39);
INSERT INTO sqlite_sequence VALUES('django_content_type',15);
INSERT INTO sqlite_sequence VALUES('auth_permission',64);
INSERT INTO sqlite_sequence VALUES('auth_group',0);
INSERT INTO sqlite_sequence VALUES('auth_user',1);
INSERT INTO sqlite_sequence VALUES('shop_author',5);
INSERT INTO sqlite_sequence VALUES('shop_publisher',3);
INSERT INTO sqlite_sequence VALUES('shop_category',5);
INSERT INTO sqlite_sequence VALUES('shop_book_author',11);
INSERT INTO sqlite_sequence VALUES('shop_book_category',11);
INSERT INTO sqlite_sequence VALUES('user_management_deliveryaddress',2);
INSERT INTO sqlite_sequence VALUES('order_order',2);
INSERT INTO sqlite_sequence VALUES('order_orderdetails',4);
INSERT INTO sqlite_sequence VALUES('shop_rating',5);
INSERT INTO sqlite_sequence VALUES('shop_book',10);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE UNIQUE INDEX "shop_book_author_book_id_author_id_31dc9d3b_uniq" ON "shop_book_author" ("book_id", "author_id");
CREATE INDEX "shop_book_author_book_id_43bcbf5f" ON "shop_book_author" ("book_id");
CREATE INDEX "shop_book_author_author_id_22efc326" ON "shop_book_author" ("author_id");
CREATE UNIQUE INDEX "shop_book_category_book_id_category_id_774eb131_uniq" ON "shop_book_category" ("book_id", "category_id");
CREATE INDEX "shop_book_category_book_id_82a3ec1c" ON "shop_book_category" ("book_id");
CREATE INDEX "shop_book_category_category_id_1bd0adc6" ON "shop_book_category" ("category_id");
CREATE INDEX "shop_rating_book_id_734d1861" ON "shop_rating" ("book_id");
CREATE INDEX "shop_rating_user_id_038b24f5" ON "shop_rating" ("user_id");
CREATE INDEX "user_management_deliveryaddress_owner_id_bb7415b3" ON "user_management_deliveryaddress" ("owner_id");
CREATE INDEX "user_management_last_viewed_books_book_id_365a32f5" ON "user_management_lastviewedbooks" ("book_id");
CREATE INDEX "user_management_last_viewed_books_owner_id_9d206250" ON "user_management_lastviewedbooks" ("owner_id");
CREATE INDEX "order_order_delivery_address_id_5e84b379" ON "order_order" ("delivery_address_id");
CREATE INDEX "order_order_owner_id_012017d7" ON "order_order" ("owner_id");
CREATE INDEX "order_orderdetails_book_id_747d89bb" ON "order_orderdetails" ("book_id");
CREATE INDEX "order_orderdetails_order_id_6b62d1e2" ON "order_orderdetails" ("order_id");
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE INDEX "shop_book_publisher_id_04743c27" ON "shop_book" ("publisher_id");
COMMIT;
