# Generated by Django 6.0.6 on 2026-07-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("card", "Card")],
                default="cash",
                max_length=20,
            ),
        ),
    ]
