# Generated by Django 6.0.6 on 2026-07-09 06:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_book_options"),
        ("user_management", "0002_remove_user_is_wholesale"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lastviewedbooks",
            options={"ordering": ["-viewed_at"]},
        ),
        migrations.AddField(
            model_name="lastviewedbooks",
            name="viewed_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="lastviewedbooks",
            unique_together={("book", "owner")},
        ),
    ]
