# Generated by Django 6.0.6 on 2026-07-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_rating_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="wholesale_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
