# Generated by Django 6.0.6 on 2026-07-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_book_wholesale_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "permissions": [("view_wholesale_price", "Can view wholesale price")]
            },
        ),
    ]
