# Generated by Django 6.0.6 on 2026-06-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publisher",
            old_name="address",
            new_name="city",
        ),
    ]
