# Generated by Django 6.0.6 on 2026-06-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_rename_address_publisher_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(related_name="books", to="shop.author"),
        ),
    ]
