# Generated by Django 6.0.6 on 2026-07-06 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_rating_book_alter_rating_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="shop.book",
            ),
        ),
    ]
