# Generated by Django 6.0.6 on 2026-07-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_wholesale",
        ),
    ]
