# Generated by Django 6.0.6 on 2026-07-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0003_alter_lastviewedbooks_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lastviewedbooks",
            name="viewed_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
